version: '3.1'
services:
  web:
    build:
      dockerfile: Dockerfile.web
    tty: true
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "8001:80"
    links:
      - db
    volumes:
      - .:/var/www/html/app
      - ./apache2:/etc/apache2
  composer:
    restart: 'no'
    image: composer:2.5
    command: install
    volumes:
      - .:/app
  db:
    build:
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: shop
    ports:
      - "8889:3306"
